### ISSUE TITLE
Cant get it to run via OTRS GenericAgent

### ISSUE THREAD

**Issue by ndom91** [magenbrot/otrs2rocket#2]
Hi MagenBrot,

I am able to execute the script manually, if I enter `. /opt/otrs2rocket/.secrets && /opt/otrs2rocket/otrs2rocket.py` on the terminal and append a valid ticket # and ticket Id, just like the genericagent job should, then it posts to Rocket.Chat as expected. 

However, the genericagent job never posts anything to rocket.chat. If I go to execute the job manually, all the tickets appear in the ticket results preview, meaning the search filter shuoldn't be filtering them out. 

I don't knwo what else to do. I adjust the python script to write a textfile with argv[1] and argv[0] every time its called, and based upon that it doiesn't look like OTRS is even executing the script, although in the genericagent overview "last executed" is always a few seconds ago after running it manually.

Am I missing something else here? Im relatively new to OTRS

**Comment by magenbrot** [comment]
Hi @ndom91, 

maybe it's a permission problem. If you followed the OTRS installation instruction the OTRS agent will run as user 'otrs'. So you'll need to make sure, that this user has access to the otrs2rocket directory and is allowed to execute the script. 
As root user you can simply do a 'su - otrs' to switch to the otrs user and test the script manually again.

best regards
Oli
